// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using NavneVelger.DataContexts;
using System;

namespace NavneVelger.Migrations
{
    [DbContext(typeof(BokerDb))]
    [Migration("20180615102849_boker")]
    partial class boker
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Panini.Entities.BokType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("BokTyper");
                });

            modelBuilder.Entity("Panini.Entities.Eier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Eiere");
                });

            modelBuilder.Entity("Panini.Entities.KlistremerkeBok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Aar");

                    b.Property<int>("EierId");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("EierId");

                    b.HasIndex("TypeId");

                    b.ToTable("Boker");
                });

            modelBuilder.Entity("Panini.Entities.Merke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BokId");

                    b.Property<int>("Nummer");

                    b.Property<bool>("klistretInn");

                    b.HasKey("Id");

                    b.HasIndex("BokId");

                    b.ToTable("Merker");
                });

            modelBuilder.Entity("Panini.Entities.KlistremerkeBok", b =>
                {
                    b.HasOne("Panini.Entities.Eier", "Eier")
                        .WithMany("Boker")
                        .HasForeignKey("EierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Panini.Entities.BokType", "Type")
                        .WithMany("Boker")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Panini.Entities.Merke", b =>
                {
                    b.HasOne("Panini.Entities.KlistremerkeBok", "Bok")
                        .WithMany("Merker")
                        .HasForeignKey("BokId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
